# Minimal kind cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: "true"
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
