apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "some-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "some-service.name" . }}
    app.kubernetes.io/instance: {{ include "some-service.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "some-service.name" . }}
      app.kubernetes.io/instance: {{ include "some-service.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "some-service.name" . }}
        app.kubernetes.io/instance: {{ include "some-service.fullname" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
